language: python
python:
  - "2.7"

before_install:
  - wget https://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix/zabbix-agent_2.2.11-1+trusty_amd64.deb
  - wget https://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix/zabbix-get_2.2.11-1+trusty_amd64.deb
  - sudo dpkg -i zabbix-agent_2.2.11-1+trusty_amd64.deb
  - sudo dpkg -i zabbix-get_2.2.11-1+trusty_amd64.deb


services:
  - elasticsearch
  -

script:
  - make continuous-test
