dist: trusty
sudo: required
group: deprecated-2017Q4
language: python
python:
  - "2.7"

env:
  - NUOVERSION=2.6.1.5 NUODB_ADD_DOMAIN_PASS=yes NUODB_START_AGENT=yes NUODB_START_REST_API=yes ES_VERSION=5.6.4 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

notifications:
  recipients:
    - tgates@nuodb.com

before_install:
  - uname -a
  - pip freeze
  - export NUODB_ROOT=/opt/nuodb
  - export NUODB_INCLUDE_DIR=/opt/nuodb/include
  - export NUODB_LIB_DIR=/opt/nuodb/lib64
  - export TZ=America/New_York
  - cat /etc/debian_version
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - sudo sh -c 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled'
  - sudo sh -c 'echo madvise > /sys/kernel/mm/transparent_hugepage/defrag'
  - wget -q http://download.nuohub.org/nuodb_${NUOVERSION}_amd64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 5
  - export NUODB_AGENTPORT=48004
  - export DOMAIN_PASSWORD=bird
  - if [[ "${NUODB_ADD_DOMAIN_PASS}" == "yes" ]] ; then sudo chmod 777 $NUODB_ROOT/etc/default.properties; printf "\ndomainPassword = ${DOMAIN_PASSWORD}\n" >> $NUODB_ROOT/etc/default.properties; sudo chmod 600 $NUODB_ROOT/etc/default.properties; fi
  - if [[ "${NUODB_START_AGENT}" == "yes" ]]; then sudo service nuoagent start; fi
  - if [[ "${NUODB_START_REST_API}" == "yes" ]]; then sudo service nuorestsvc start; fi
  - ${NUODB_ROOT}/bin/nuodbmgr --broker localhost --password bird --command "start process sm host localhost database test archive /var/tmp/nuodb initialize true"
  - ${NUODB_ROOT}/bin/nuodbmgr --broker localhost --password bird --command "start process te host localhost database test options '--dba-user dba --dba-password dba'"
  - ${NUODB_ROOT}/bin/nuosql test@localhost --user dba --password dba < tests/etc/create_user_cloud.sql

install:
  - pip install -r requirements.txt

script:
  - printenv
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - curl -XGET http://localhost:9200
  - tests/etc/elastic_search/es_test_create_index.sh
  - make zabbix
  - make logstash
  - source etc/nuoca_env.sh
  - make continuous-test
