# The following URL is the one provisioned by NuoDB for gathering health check
# data to contribute to the quality of the product.
#hc.collector: "http://52.23.241.226/hc/"

# The following URL is one used for development testing purposes only and serves
# only to test exercise the POSTing capability of the HC tool.
#hc.collector: "http://52.23.241.226/hc/"
#nuodb.mngr.password: "bird"
#nuodb.mngr.hostport: "localhost"
#nuosql.user: "dba"
#nuosql.password: "dba"
#nuosql.database: "nuodb@localhost:48004"
